---
- hosts: all
  become: true

  tasks:

    - name: Add to .bashrc for `sol` user
      ansible.builtin.blockinfile:
        path: /home/sol/.bashrc
        insertbefore: EOF
        block: "{{ item }}"
      with_items:
        - "{{lookup('ansible.builtin.file', '{{pwd}}/content/bashrc_addition') }}"